### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by Sheljohn** [ketch/nodepy#31]
There are numerous patches displaying an error notice in the [latest documentation](http://nodepy.readthedocs.io/en/latest/rkm.html), which suggests the latest build failed. The timestamps suggest this was in 2015.

Some badges on the README page appear to be broken links too, and most open issues date back to 2015 as well.

I realise the maintenance of such a package is a lot of work, but for information and as a user, should this package be considered deprecated?

**Comment by ketch** [comment]
Readthedocs seems to have made changes that broke sphinx autodoc, and the fix breaks other things for nodepy; see #32.  Thanks for alerting me to this.  In the meantime, building the docs locally should work fine.

"Deprecated" implies that there is something newer/better to use, so the package certainly isn't deprecated.  Patches are welcome!

**Comment by ketch** [comment]
FYI it seems that everything works correctly now on readthedocs.  Please let me know if you still find errors.
