### ISSUE TITLE
Circular dependency?

### ISSUE THREAD

**Issue by mikaem** [ketch/nodepy#33]
With Python 3.4 I'm getting

    `----> 1 import nodepy

    /home/mikael/MySoftware/nodepy/nodepy/__init__.py in <module>()
        5 __version__="0.6.1"
        6 
    ----> 7 import nodepy.runge_kutta_method as rk
        8 import nodepy.twostep_runge_kutta_method as tsrk
        9 import nodepy.downwind_runge_kutta_method as dwrk

    /home/mikael/MySoftware/nodepy/nodepy/runge_kutta_method.py in <module>()
        58 
        59 import nodepy.snp as snp
    ---> 60 from nodepy.general_linear_method import GeneralLinearMethod
        61 
        62 #=====================================================

    /home/mikael/MySoftware/nodepy/nodepy/general_linear_method.py in <module>()
    ----> 1 from nodepy.ode_solver import ODESolver
        2 import nodepy.rooted_trees as rt
        3 
        4 #=====================================================
        5 class GeneralLinearMethod(ODESolver):

    /home/mikael/MySoftware/nodepy/nodepy/ode_solver.py in <module>()
        3 
        4 import numbers
    ----> 5 import runge_kutta_method as rk
        6 
        7 #=====================================================

    ImportError: No module named 'runge_kutta_method'
    `
Works fine with Python 2, but not 3. A possible fix as I see it is to put the `import runge_kutta_method as rk` within `ode_solver.py` inside the `__call__` method of `ODESolver`.
The error breaks spectralDNS builds on Python3.4!

**Comment by ketch** [comment]
This should be fixed now (not in a perfect way, but good enough...)

**Comment by mikaem** [comment]
Great! Didn't want to suggest a trivial PR because I suspected you'd want to do something like this:-) Now if you could also fix the tab issue that Python 3.4 doesn't seem to like [https://github.com/mikaem/nodepy/commit/b511e009a9e16c2a198c2aa0f5f18225830c930c](url) and https://travis-ci.org/spectralDNS/spectralDNS/jobs/173267356 , then I could delete my fork:-)

**Comment by ketch** [comment]
Done!  (I think).
